before_install:
  - wget -c https://github.com/coreos/etcd/releases/download/v2.0.0-rc.1/etcd-v2.0.0-rc.1-linux-amd64.tar.gz
  - tar -zxf etcd-v2.0.0-rc.1-linux-amd64.tar.gz
  - gem update bundler
  - bundle install

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
branches:
  only:
    - master
script: "ETCD_BIN=./etcd-v2.0.0-rc.1-linux-amd64/etcd bundle exec rake spec"
